repos:
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        files: ^(backend|packages)/.*\.py$
-   repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        files: ^(backend|packages)/.*\.py$
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
        files: ^(backend|packages)/.*\.py$
        args: [--ignore-missing-imports]